[project]
name = "bustimer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "polars>=1.37.1",
    "requests>=2.32.5",
]
